version: "3.7"
services:
  atm-db:
    container_name: atm-db
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db/data:/var/lib/mysql
      - ./db/config/custom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: unless-stopped
    networks:
      - atm-web

  bankaccount-api:
    container_name: bankaccount-api
    build:
      context: bankaccount-api/.
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
    depends_on:
      - atm-db
    networks:
      - atm-web

  atm-web:
    container_name: atm-web
    build:
      context: atm-web/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - atm-db
      - bankaccount-api
    networks:
      - atm-web

networks:
  atm-web:
    name: atm-web
    driver: bridge